### ISSUE TITLE
EAP Feature Access Request: Storage & Auth

### ISSUE THREAD

**Issue by VishnuSanal** [openmobilehub/admin#1]
**Feature Requested:**
- Storage
- Auth

**Organization Details:**
- **Company/Organization Name:** Team Amaze
- **Contact Name:** Vishnu Sanal T
- **Role/Position:** Maintainer/Contributor
- **Email Address:** t.v.s10123@gmail.com

**Project Details:**
- **Use Case Description:** the storage SDK can be integrated with our cloud plugin that provides the users access to google drive, dropbox, onedrive & box.
- **GitHub Repository URL:** https://github.com/TeamAmaze/AmazeCloud/

**Additional Information:**

**Feedback Commitment:**
- I would like to work on and contribute to the development of OMH plugins!

Best regards,

Vishnu Sanal T
Contributor & Maintainer
Team Amaze
t.v.s10123@gmail.com

---

This template is designed to be filled out with your specific details and needs. Providing comprehensive information will help us understand how the requested OMH EAP feature can support your project and enable us to process your request more efficiently.

**Comment by dzuluaga** [comment]
@VishnuSanal - Please share your GH handles. Thanks!

**Comment by VishnuSanal** [comment]
> @VishnuSanal - Please share your GH handles. Thanks!

@TranceLove @VishalNehra @EmmanuelMess @VishnuSanal

edit: ping @dzuluaga

**Comment by dzuluaga** [comment]
@VishnuSanal sorry for the delay. You should have access now. Please share with us your feedback. Here are our [EAP guidelines](https://docs.google.com/presentation/d/1LPGyQ7jBWOEKbQfy-9D8TbKtORBWn_bOyzN8VwrXhrI/edit#slide=id.g2c875bc703a_1_65) for EAP.

Storage hasn't started yet. Please continue to join the TSC meetings to get updates.
